version: '3.8'
services:
  watcher:
    container_name: watcher
    image: scallme/spread-watcher-backend:latest
    logging:
        options:
          max-size: "200k"
          max-file: "10"
    environment: 
      DEBUG_MODE: true
      BINANCE_API_KEY: 6sXMRvvFBADvXeFP5NsHWKmh8F0IISrtKtRgvu6LgZXWHjPrMYX1YYfUdhFt5xLL
      BINANCE_API_SECRET: xImDnuc8IeYWKc5H0ZxVC8rlSTIaSSI48yk9S8dduEbX9duN3tCbM0ERUfgMudGn
      KUCOIN_API_KEY: 66ae59b162f18d00010176f7
      KUCOIN_API_SECRET: c6fd993c-379c-42d1-b0a6-148f8db0e933
      KUCOIN_API_PASSPHRASE: li303zd6
      GATEIO_API_V2_KEY: 9A265598-8D90-4B2C-A909-09E3C9C8F992
      GATEIO_API_V2_SECRET: 162a3cb1f57a497dce090cc01e86854514a888c8c9864df357182446c3fcc627
      GATEIO_API_V4_KEY: c33bc07eb2cc70200ebfd42edc7fc0f4
      GATEIO_API_V4_SECRET: 275207ff720e8357a8920c5a010b2d57358cc4ca638a1700ae33ece3bbe21216
      SPREAD_MINIMAL: 0
      QUANTITY_MINIMAL_USDT: 0
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: watcher_data
      DB_COLLECTION: spreads
  dashboard:
    container_name: dashboard
    image: scallme/spread-watcher-dashboard:latest
    ports:
      - 3000:3000
    environment: 
      SECRET_KEY_BASE: 629a95a7e255e6adfeecc7e97752da3740a183ec8c188a0120c7c8f6d60a7496a67fc168ce046e1dc2016c42f402fc3e1b3a97629e2e969c8424d3bf3e2ab8a2
  mongodb:
    container_name: mongodb
    image: mongo:7.0
    command: mongod --noauth
    logging:
        options:
          max-size: "200k"
          max-file: "10"
    #ports:
    #  - 27017:27017
