version: '3.8'
services:
  dashboard:
    container_name: dashboard
    image: devflexpro/spread-watcher-dashboard:latest
    ports:
      - 3000:3000
    environment: 
      - SECRET_KEY_BASE: 629a95a7e255e6adfeecc7e97752da3740a183ec8c188a0120c7c8f6d60a7496a67fc168ce046e1dc2016c42f402fc3e1b3a97629e2e969c8424d3bf3e2ab8a2
  mongodb:
    container_name: mongodb
    image: mongo:7.0
    command: mongod --noauth
    logging:
        options:
          max-size: "200k"
          max-file: "10"
    #ports:
    #  - 27017:27017
